[package]
org = "user"
name = "PMS"
version = "0.1.0"
distribution = "2201.8.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
path = "/usr/share/java/mysql-connector-j-8.1.0.jar"

USER="root"
# PASSSWORD="100101"
HOST="127.0.0.1"
PORT=3306
DATABASE="PMS_DB"

PASSWORD = "100101"	# Type of STRING
